version: '3'

services: 
  postgres:
    image: postgres:latest
    ports:
    - "5433:5432"
    networks:
    - etl_network
    environment: 
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: secret

  etl_script:
    build:
      context: ./src
      dockerfile: Dockerfile 
    command: ["python", "csv_etl_script.py"]
    networks:
      - etl_network
    depends_on:
      - postgres

networks:
  etl_network:
    driver: bridge