services: 
  postgres:
    image: postgres:latest
    ports:
    - "5434:5432"
    networks:
    - etl_network
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  etl_script:
    build:
      context: ./src
      dockerfile: Dockerfile 
    command: ["python", "csv_etl_script.py"]
    networks:
      - etl_network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    env_file:
      - .env

networks:
  etl_network:
    driver: bridge