services: 
  postgres:
    image: postgres:latest
    ports:
    - "5434:5432"
    networks:
    - etl_network
    environment: 
      POSTGRES_DB: f1_database
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: secret
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  etl_script:
    build:
      context: ./src
      dockerfile: Dockerfile 
    command: ["python", "csv_etl_script.py"]
    networks:
      - etl_network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data

networks:
  etl_network:
    driver: bridge